### PR TITLE
[SDP-1014] Preload reCAPTCHA script in attempt to mitigate component loading issues upon login

### PR DESCRIPTION
**Pull request by ziyliu**
### What
Modify the receiver registration template to preload the google recaptcha script in the header instead of doing so in the body.

### Why
@torisamples brought up this [issue](https://stellarfoundation.slack.com/archives/C04C9MLM9UZ/p1702420198999679) of the recaptcha taking too long to load or not loading at all at times. Preloading the script may help with the slowness.

### Known limitations

[TODO or N/A]

#### PR Structure

* [x] This PR has a reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR title and description are clear enough for anyone to review it.
* [x] This PR does not mix refactoring changes with feature changes (split into two PRs otherwise).

#### Thoroughness

* [x] This PR adds tests for the new functionality or fixes.
* [x] This PR contains the link to the Jira ticket it addresses.

#### Configs and Secrets

* [x] No new CONFIG variables are required -OR- the new required ones were added to the helmchart's [`values.yaml`] file.
* [x] No new CONFIG variables are required -OR- the new required ones were added to the deployments ([`pr-preview`], [`dev`], [`demo`], `prd`).
* [x] No new SECRETS variables are required -OR- the new required ones were mentioned in the helmchart's [`values.yaml`] file.
* [x] No new SECRETS variables are required -OR- the new required ones were added to the deployments ([`pr-preview secrets`], [`dev secrets`], [`demo secrets`], `prd secrets`).

#### Release

* [x] This is not a breaking change.
* [x] **This is ready for production.**. If your PR is not ready for production, please consider opening additional complementary PRs using this one as the base. Only merge this into `develop` or `main` after it's ready for production!

#### Deployment

* [ ] Does the deployment work after merging?

[`values.yaml`]: ../helmchart/sdp/values.yaml
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disbursement-platform/backend-helm-values
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend-helm-values
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend-helm-values
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L346
[`dev secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/stellar-disbursement-platform-externalsecrets.yaml
[`demo secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-sdp-externalsecrets.yaml

### CODE REVIEW

**Comment by ziyliu** [comment]
@quietbits may need to work with you to test it
Tori said that she's noticed the slowness when 
> A) bandwidth is low
> B) I haven’t loaded that page in a long time.
>

**Review by CaioTeixeira95 — APPROVED** [review]
TIL

**Review by quietbits — APPROVED** [review]
Looking at the network requests, it doesn't seem like this update makes much difference in how the files are loaded. This may be because this is the only external script we're using, and all the other scripts are local, so the result is the same.

On slow connections, I notice that it takes a while for reCaptcha to load fully, and there is no indication on the UI that something is still loading (all the other pieces are already loaded). Maybe there is something in reCaptcha we can use on the frontend to improve the UX.

**Comment by ziyliu** [comment]
@quietbits @torisamples I added a `preconnect` resource for the google api link in the tmpl, and I do notice a significant decrease in loading time from opening up the connection ahead of time. but like iveta mentioned, there isn't a placeholder to indicate that there will be a recaptcha component on the pg until the script has finished downloading.

**Pull request merged**
