### PR TITLE
wallets - Add Freedom Wallet

### PR DESCRIPTION
**Pull request by yuriescl**
### What

Add support for the Freedom Wallet.

### Why

Freedom Wallet is already being used in Gambia to allow communites to receive SDP disbursements, it would be great to have it listed as one of the wallets.

### Known limitations

[TODO or N/A]

#### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR does not mix refactoring changes with feature changes (split into two PRs otherwise).
* [x] This PR's title starts with the name of the package, area, or subject affected by the change.

#### Thoroughness

* [ ] This PR adds tests for the new functionality or fixes. - **I'm not sure which tests to add or modify - please guide me if possible**
* [ ] This PR contains the link to the Jira ticket it addresses.

#### Configs and Secrets

* [x] No new CONFIG variables are required -OR- the new required ones were added to the helmchart's [`values.yaml`] file.
* [x] No new CONFIG variables are required -OR- the new required ones were added to the deployments ([`pr-preview`], [`dev`], [`demo`], `prd`).
* [x] No new SECRETS variables are required -OR- the new required ones were mentioned in the helmchart's [`values.yaml`] file.
* [x] No new SECRETS variables are required -OR- the new required ones were added to the deployments ([`pr-preview secrets`], [`dev secrets`], [`demo secrets`], `prd secrets`).

#### Release

* [x] This is not a breaking change.
* [x] **This is ready for production.**. If your PR is not ready for production, please consider opening additional complementary PRs using this one as the base. Only merge this into `develop` or `main` after it's ready for production!

#### Deployment

* [ ] Does the deployment work after merging?

[`values.yaml`]: ../helmchart/sdp/values.yaml
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disbursement-platform/backend-helm-values
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend-helm-values
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend-helm-values
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L346
[`dev secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/stellar-disbursement-platform-externalsecrets.yaml
[`demo secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-sdp-externalsecrets.yaml

### CODE REVIEW

**Comment by marwen-abid** [comment]
@yuriescl we really appreciate your contribution and happy to hear that SDP and Freedom wallet are being used in Gambia! 

Your PR looks great. I'm working on fixing the tests as they're currently not accommodating to contributors merging from forks. I should have a fix for that shortly. 

The one thing we would love to see is a short video/demo that shows Freedom Wallet being used to receive funds from an SDP instance. 
Once we get that I'll merge your PR and Freedom wallet will be available on version 1.0.1 of the SDP.

**Comment by yuriescl** [comment]
> The one thing we would love to see is a short video/demo that shows Freedom Wallet being used to receive funds from an SDP instance.

Sure, we can provide a video but it will likely contain private info (names, phones, etc). Is there a way we can provide you the video in a private manner?

**Comment by marwen-abid** [comment]
> > The one thing we would love to see is a short video/demo that shows Freedom Wallet being used to receive funds from an SDP instance.
> 
> Sure, we can provide a video but it will likely contain private info (names, phones, etc). Is there a way we can provide you the video in a private manner?

@yuriescl You can send it to me by email at `marwen.abid@stellar.org`. Thank you!

**Comment by clarsen-bpv** [comment]
> @yuriescl You can send it to me by email at marwen.abid@stellar.org. Thank you!

@marwen-abid I have sent you an email with the materials requested, many thanks for your support!

**Review by marwen-abid — APPROVED** [review]
This looks great! Thank you to the team @yuriescl @clarsen-bpv for providing all the resources and very excited to see more usage of Freedom Pay wallet with the SDP.

**Comment by marcelosalloum** [comment]
Hey @yuriescl, these links are currently broken. Is this wallet working in production? Otherwise, we'll consider removing these links.

Thank you

**Comment by yuriescl** [comment]
Hi @marcelosalloum I am not involved with the project, please consult BP Ventures.

**Comment by yuriescl** [comment]
@antb123

**Pull request merged**
